// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnAL1_Knsybm5UqXq3Q-xPS81iLwDlgyw',
    appId: '1:53611106398:android:5837f9ed6a3369544fe4cf',
    messagingSenderId: '53611106398',
    projectId: 'the-hit-times-v2',
    databaseURL: 'https://the-hit-times-v2.firebaseio.com',
    storageBucket: 'the-hit-times-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApvaRthtn5fI4A-iNufZs0qCNZA7t2h54',
    appId: '1:53611106398:ios:d73cc051be15a9a04fe4cf',
    messagingSenderId: '53611106398',
    projectId: 'the-hit-times-v2',
    databaseURL: 'https://the-hit-times-v2.firebaseio.com',
    storageBucket: 'the-hit-times-v2.firebasestorage.app',
    androidClientId: '53611106398-mik3s4vcj1cujc466msftks3cbk2g7c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.theHitTimesApp',
  );
}
